spring:
    cloud:
    stream:
      function:
        definition: supply1;supply2
      bindings:
        supply1-out-0:
          destination: queue1
        supply2-out-0:
          binder: servicebus-2
          destination: queue2

      binders:
        servicebus-1:
          type: servicebus-queue
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://servicebus-xiaozhu-1.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=rlkgPRKENhqLAM7d5qMOtdDPLTF0OHLDS6SX7yeocLc=
        servicebus-2:
          type: servicebus-queue
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://servicebus-xiaozhu-1.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=rlkgPRKENhqLAM7d5qMOtdDPLTF0OHLDS6SX7yeocLc=
      servicebus:
        queue:
          bindings:
            consume1-in-0:
              consumer:
                checkpoint-mode: MANUAL
            consume2-in-0:
              consumer:
                checkpoint-mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000

    profiles:
        active: manual
debug: true
